// Package keys defines an OS-independent set of key names used on the wire
// so a controller on one platform can drive a target on another. Platform
// packages (capture/inject) each provide a mapping between this set and
// their native key codes.
package keys

type Name string

const (
	A Name = "A"
	B Name = "B"
	C Name = "C"
	D Name = "D"
	E Name = "E"
	F Name = "F"
	G Name = "G"
	H Name = "H"
	I Name = "I"
	J Name = "J"
	K Name = "K"
	L Name = "L"
	M Name = "M"
	N Name = "N"
	O Name = "O"
	P Name = "P"
	Q Name = "Q"
	R Name = "R"
	S Name = "S"
	T Name = "T"
	U Name = "U"
	V Name = "V"
	W Name = "W"
	X Name = "X"
	Y Name = "Y"
	Z Name = "Z"

	N0 Name = "N0"
	N1 Name = "N1"
	N2 Name = "N2"
	N3 Name = "N3"
	N4 Name = "N4"
	N5 Name = "N5"
	N6 Name = "N6"
	N7 Name = "N7"
	N8 Name = "N8"
	N9 Name = "N9"

	F1  Name = "F1"
	F2  Name = "F2"
	F3  Name = "F3"
	F4  Name = "F4"
	F5  Name = "F5"
	F6  Name = "F6"
	F7  Name = "F7"
	F8  Name = "F8"
	F9  Name = "F9"
	F10 Name = "F10"
	F11 Name = "F11"
	F12 Name = "F12"

	Enter        Name = "Enter"
	Escape       Name = "Escape"
	Space        Name = "Space"
	Tab          Name = "Tab"
	Backspace    Name = "Backspace"
	Delete       Name = "Delete"
	Insert       Name = "Insert"
	Home         Name = "Home"
	End          Name = "End"
	PageUp       Name = "PageUp"
	PageDown     Name = "PageDown"
	CapsLock     Name = "CapsLock"
	ArrowLeft    Name = "ArrowLeft"
	ArrowRight   Name = "ArrowRight"
	ArrowUp      Name = "ArrowUp"
	ArrowDown    Name = "ArrowDown"
	ShiftLeft    Name = "ShiftLeft"
	ShiftRight   Name = "ShiftRight"
	ControlLeft  Name = "ControlLeft"
	ControlRight Name = "ControlRight"
	AltLeft      Name = "AltLeft"
	AltRight     Name = "AltRight"
	MetaLeft     Name = "MetaLeft"
	MetaRight    Name = "MetaRight"

	Minus        Name = "Minus"
	Equal        Name = "Equal"
	LeftBracket  Name = "LeftBracket"
	RightBracket Name = "RightBracket"
	Backslash    Name = "Backslash"
	Semicolon    Name = "Semicolon"
	Quote        Name = "Quote"
	Comma        Name = "Comma"
	Period       Name = "Period"
	Slash        Name = "Slash"
	Grave        Name = "Grave"
)
